config_version: 4
log_level: info
token_usage:
  enabled: false
models:
- name: deepseek-v3
  display_name: DeepSeek V3 (Thinking)
  use: deerflow.models.patched_deepseek:PatchedChatDeepSeek
  model: deepseek-reasoner
  api_key: sk-48a14fab60334dd792aa08f19d65f54b
  max_tokens: 8102
  supports_thinking: true
  supports_vision: false
  when_thinking_enabled:
    extra_body:
      thinking:
        type: enabled
- name: local-llm
  display_name: Local LLM (TGI)
  use: langchain_openai:ChatOpenAI
  model: mssgpt
  base_url: http://192.168.8.157:8103/ChatModelServing/v1
  api_key: EMPTY
  max_tokens: 4096
  temperature: 0.01
  supports_thinking: true
  supports_vision: false
tool_groups:
- name: web
- name: file:read
- name: file:write
- name: bash
tools:
- name: web_search
  group: web
  use: deerflow.community.internal_search.tools:web_search_tool
  base_url: http://192.168.82.122:8080/api/search
  top_k: 5
- name: ls
  group: file:read
  use: deerflow.sandbox.tools:ls_tool
- name: read_file
  group: file:read
  use: deerflow.sandbox.tools:read_file_tool
- name: write_file
  group: file:write
  use: deerflow.sandbox.tools:write_file_tool
- name: str_replace
  group: file:write
  use: deerflow.sandbox.tools:str_replace_tool
- name: bash
  group: bash
  use: deerflow.sandbox.tools:bash_tool
tool_search:
  enabled: false
sandbox:
  use: deerflow.sandbox.local:LocalSandboxProvider
skills:
  container_path: /mnt/skills
title:
  enabled: true
  max_words: 6
  max_chars: 60
  model_name: null
summarization:
  enabled: true
  model_name: null
  trigger:
  - type: tokens
    value: 155640
  keep:
    type: messages
    value: 50
  trim_tokens_to_summarize: 155640
  summary_prompt: null
database:
  url: mysql+aiomysql://823admin:DATABASE_treeshade_2024_04@192.168.8.131:3306/aiwriting
  pool_size: 10
  max_overflow: 20
memory:
  enabled: true
  storage_class: deerflow.agents.memory.mysql_storage.MySQLMemoryStorage
  storage_path: memory.json
  debounce_seconds: 30
  model_name: null
  max_facts: 100
  fact_confidence_threshold: 0.7
  injection_enabled: true
  max_injection_tokens: 2000
checkpointer:
  type: postgres
  connection_string: postgresql://postgres:841_sjzc@192.168.82.122:5432/deerflow
citation_verification:
  enabled: false
  strictness: warn
  long_text_threshold: 1000
  tracked_tools:
  - web_search
  - web_fetch
  - jina_fetch
